@startuml

title Top-level Module structure

'Instructions:
'This codebase is utilizing ports-and-adaptor and DI to ensure code cleanliness & prevent circular
'dependencies.
'Each direct child of root module (wordle) is an organisation module. If any component of an organisational
'module imports another organisational model, record it in this module graph. Ensure that no circular
'dependencies occur.

'Test module can be disregarded for this purpose

[play_cli] --> [game]
note top of play_cli
    Entry point - play game via CLI
end note

[play_cli] --> [models]
[play_cli] --> [errors]

[solver_cli] --> [pattern_solver]
note top of solver_cli
    Entry point - invoke automated solvers
end note

[solver_cli] --> [game]

[pattern_solver] --> [models]
[pattern_solver] --> [game_api]

[game] --> [models]
[game] --> [game_api]

[game_api] --> [models]

[models] -> [errors]

@enduml
